services:
  - type: web
    name: college-events-backend
    env: node
    rootDir: backend
    buildCommand: |
      cd ../frontend && npm install && npm run build && cp -r dist ../backend/frontend-dist
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
